apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerdemo
  labels:
    app: dockerdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerdemo
  template:
    metadata:
      labels:
        app: dockerdemo
    spec:
      containers:
        - name: dockerdemo
          image: sambagurd/dockerdemo
          ports:
            - containerPort: 80
